### ISSUE TITLE
Possible improvements

### ISSUE THREAD

**Issue by davidweterings** [Heffie/postbode-python#1]
Some improvements to think about:

Must have:
- define dependencies in setup.py (you're depending on requests, which is not installed by default in all setups)
- Some tests using py-test and requests mocker
- send_letters should call send_letter, and return the response data

Should have:
- Use a logger instead of printing errors. Note if someone want to debug requests they can change the requests logger, so instead you could do `response.raise_for_status()` and let the caller handle it from there.
- Add typing to all functions
- Consider using a Requests Session object to set the headers once and also get performance improvements since it would use the same connection for multiple calls
- Use black and isort to format code consistently

Nice to have:
- Consider using bumpversion to create tagged releases
- Github actions to run tests
- Github action to trigger release to pypi
- Add tox for testing multiple python versions

**Comment by Heffie** [comment]
Hi David, 

Thanks for the elaborate and spot on suggestions. I've implemented all of them since 0.1.3
